spring:
    application:
        name: sso-microservice

server:
    port: 8091
    servlet:
        context-path: /sso-microservice

cloud:
    aws:
        paramstore:
            enabled: true
        region:
            static: ${cloud.aws.region.static}
        stack:
            auto: false

br:
    tec:
        plin:
            resource-account-url: http://localhost:8090/
